customhost = "employee-db1.caqql7yp67s6.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee-db1"
custombucket = "employee-db-demo"
customregion = "us-east-1"
